### PR TITLE
Added week support.

### PR DESCRIPTION
**Pull request by EdwardSalter**
Enables week data to be pulled from the CLDR.

This is working towards completing https://github.com/yahoo/react-intl/issues/820.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by EdwardSalter** [comment]
I have accepted the CLA but the check is still showing as failed. Is it possible to re-run it without abandoning the PR and creating a new one?

**Comment by MelisaIm** [comment]
Would love to see this feature, when can it be merged in? @yahoocla @EdwardSalter

**Comment by artursvonda** [comment]
Any progress on this feature? Can I help?

**Comment by okuryu** [comment]
it seems to need resolve conflicts. otherwise I'm ok on this.

**Comment by artursvonda** [comment]
Created a new PR (https://github.com/yahoo/formatjs-extract-cldr-data/pull/22) since can't edit this

**Comment by redonkulus** [comment]
Closed via https://github.com/formatjs/formatjs-extract-cldr-data/pull/22

**Pull request closed without merging**
