### PR TITLE
Extract week data

### PR DESCRIPTION
**Pull request by artursvonda**
Add week support

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by artursvonda** [comment]
https://github.com/yahoo/formatjs-extract-cldr-data/pull/14 Looks to be abandoned and I can't edit so I just created a new PR. Do I need to update anything else?

**Comment by artursvonda** [comment]
Signed the CLA

**Comment by redonkulus** [comment]
Can you add a unit test for this?

**Comment by artursvonda** [comment]
Added a simple test. Not sure if anything more is needed. Let me know if so.

**Pull request merged**
